{% set provider = "oauth2-proxy" %}
{% set goname = "github.com/oauth2-proxy/oauth2-proxy" %}
{% set version = "7.11.0" %}

{% set name = "oauth2-proxy" %}
{% set pkg_src = "src/github.com/oauth2-proxy/oauth2-proxy" %}

package:
  name: oauth2-proxy
  version: {{ version }}

source:
  - folder: src/github.com/oauth2-proxy/oauth2-proxy
    url: https://github.com/oauth2-proxy/oauth2-proxy/archive/v{{ version }}.tar.gz
    sha256: 1c32bdf0b9650730cf5f22f02e6f1fc628cd6a25617a076dc9d551a65a29e9b0

build:
  number: 0
  script:
    - pushd src/github.com/oauth2-proxy/oauth2-proxy
    - GOBIN=$(go env GOBIN)  # [not win]
    - if [ -z "$GOBIN" ]; then GOBIN="$PREFIX/bin"; fi  # [not win]
    - FOR /F "delims=" %%i IN ('go env GOBIN') DO set "GOBIN=%%i"  # [win]
    - if "%GOBIN%"=="" set "GOBIN=%PREFIX%\bin"  # [win]
    - go build -v -o $GOBIN/oauth2-proxy .       # [unix]
    - go build -v -o %GOBIN%\oauth2-proxy.exe .  # [win]

requirements:
  build:
    - go-nocgo

test:
  requires:
    - m2-bash       # [win]
    - m2-coreutils  # [win]

  commands:
    - oauth2-proxy --version

about:
  home: https://github.com/oauth2-proxy/oauth2-proxy
  license: MIT
  license_file: src/github.com/oauth2-proxy/oauth2-proxy/LICENSE
  summary: A reverse proxy and static file server that provides authentication using Providers (Google, GitHub, and others) to validate accounts by email, domain or group.
  doc_url: https://oauth2-proxy.github.io/oauth2-proxy/
  dev_url: https://github.com/oauth2-proxy/oauth2-proxy

extra:
  recipe-maintainers:
    - asford
    - mxr-conda
    - rluria14
    - ndmaxar
    - oblute
    - RyanHackney
