{% set provider = "oauth2-proxy" %}
{% set goname = "github.com/oauth2-proxy/oauth2-proxy" %}
{% set version = "7.11.0" %}

{% set name = "oauth2-proxy" %}
{% set pkg_src = "src/github.com/oauth2-proxy/oauth2-proxy" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: 1c32bdf0b9650730cf5f22f02e6f1fc628cd6a25617a076dc9d551a65a29e9b0

build:
  number: 0
  script:
    - pushd {{ pkg_src }}  # [unix]
    - cd /d {{ pkg_src }}  # [win]
    - go build -v -o $PREFIX/bin/{{ name }} .       # [unix]
    - go build -v -o %PREFIX%\bin\{{ name }}.exe .  # [win]

requirements:
  build:
    - {{ compiler('go') }}

test:
  requires:
    - m2-bash       # [win]
    - m2-coreutils  # [win]

  commands:
    - {{ name }} --version

about:
  home: https://{{ goname }}
  license: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: A reverse proxy and static file server that provides authentication using Providers (Google, GitHub, and others) to validate accounts by email, domain or group.
  doc_url: https://{{ provider }}.github.io/{{ provider }}/
  dev_url: https://{{ goname }}

extra:
  recipe-maintainers:
    - asford
    - mxr-conda
    - rluria14
    - ndmaxar
    - oblute
    - RyanHackney
